# Site settings
name: Andy's Blog
email: zhang_shouzheng@163.com
author: Andy zhang
url: http://www.hifreud.com
resume_site: http://www.hifreud.com
github: https://github.com/rareloved/
baseurl: ""
description: Action, life is never stop!
meta_description: 张首正;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Time and tide wait for no man.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: rareloved

# Build settings
markdown: kramdown
highlighter: pygments

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

